### PR TITLE
xraylarch: initial rerender

### PR DESCRIPTION
**Pull request by mrakitin**
Based on https://github.com/NSLS-II/lightsource2-recipes/tree/master/recipes-tag/xraylarch.

### CODE REVIEW

**Comment by mrakitin** [comment]
We are only missing the `tomopy` beast here:
https://github.com/nsls-ii-forge/xraylarch-feedstock/blob/9a023c3d043a9e4a086ca191f9497d08647806b8/recipe/meta.yaml#L51

Will come next.

**Comment by mrakitin** [comment]
Power-cycled to pick up `tomopy` from https://github.com/nsls-ii-forge/tomopy-feedstock/pull/1.

**Review by tacaswell — APPROVED** [review]

**Comment by mrakitin** [comment]
Something went wrong:
```
    error: package directory 'larch/bin' does not exist
```

**Comment by mrakitin** [comment]
@tacaswell, do you think we should remove these lines as well?
https://github.com/nsls-ii-forge/xraylarch-feedstock/blob/c196fcbe873536f67e43177080b8484470411dbe/recipe/meta.yaml#L21-L22

**Comment by tacaswell** [comment]
force-pushed a fix.

**Comment by mrakitin** [comment]
Thanks. There are a few more libraries added in `larch/bin`, do we still want to carry all of them?
image

**Comment by tacaswell** [comment]
You can never be sure what weird linking things are going on.  I suspect if we check the `ldd` it is going to find those.

**Pull request merged**
